/// Flutter icons Menu
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Menu
///      fonts:
///       - asset: fonts/Menu.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Menu {
  Menu._();

  static const _kFontFam = 'Menu';
  static const String? _kFontPkg = null;

  static const IconData group_21 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
